import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/header";
import "./globals.css";
import Providers from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Practice Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='bg-base-200'>
      <body className={inter.className}>
      <Navbar />
      <main className='px-8 py-20 max-w-6xl mx-auto'>
          <Providers>
              {children}
          </Providers>
      </main>
      </body>
    </html>
  );
}
